apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-cluster-liveness
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: etcd-cluster-liveness
  template:
    metadata:
      labels:
        name: etcd-cluster-liveness
    spec:
      serviceAccountName: cilium-etcd-sa
      hostNetwork: true
      containers:
      - name: etcd-cluster-liveness
        image: lachlanevenson/k8s-kubectl
        command:
        - sh
        - /scripts/etcd-liveness-check.sh
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "20Mi"
            cpu: "100m"
          limits:
            memory: "50Mi"
            cpu: "200m"
        volumeMounts:
        - mountPath: /scripts
          name: scripts
      volumes:
      - name: scripts
        configMap:
          name: etcd-liveness-check
